-- Date columns are naive `timestamp` (no time zone), matching Core's exact
-- column types (migrations/0006_org_roles_resources.sql:30-31 and the live
-- DB's information_schema) so the 0002 copy migration's INSERT ... SELECT
-- from public.* is a plain same-type copy, not an implicit
-- timestamp -> timestamptz cast whose result depends on the session's
-- TimeZone GUC. Defaults still use now().
CREATE TABLE organizations (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  address    text,
  verified   boolean NOT NULL DEFAULT false,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE memberships (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  org_ref    integer NOT NULL REFERENCES organizations(id),
  user_ref   integer NOT NULL,
  role       text NOT NULL CHECK (role IN ('owner','admin','member')),
  created_at timestamp NOT NULL DEFAULT now(),
  CONSTRAINT memberships_user_uq UNIQUE (user_ref)
);
--> statement-breakpoint
CREATE INDEX memberships_org_idx ON memberships (org_ref);
--> statement-breakpoint
CREATE TABLE org_secrets (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_ref         integer NOT NULL REFERENCES organizations(id),
  name            text NOT NULL,
  encrypted_value text NOT NULL,
  broker_type     text,
  is_test_account boolean NOT NULL DEFAULT false,
  created_by      integer,
  created_at      timestamp NOT NULL DEFAULT now(),
  updated_at      timestamp NOT NULL DEFAULT now(),
  CONSTRAINT org_secrets_org_name_uq UNIQUE (org_ref, name)
);
