import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Bell, Mail, Radio, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Label, Tabs, TabsContent, TabsList, TabsTrigger, apiRequest, queryClient } from "@vox/web-plugin-sdk";
import type { RuleDefinition } from "../configuration";

const base = "/api/plugins/notifications";
const selectStyle = "h-10 w-full rounded-md border border-input bg-background px-3 text-sm";
const textareaStyle = "min-h-28 w-full rounded-md border border-input bg-background p-3 text-sm";
interface Permission { isAdmin: boolean; canEdit: boolean; canScript: boolean; canLlm: boolean; groupIds: string[]; }
interface Group { id: string; name: string; user_refs?: number[]; }
interface Settings { permission: Permission; groups: Group[]; metrics: string[]; emailAvailable: boolean; encryptionConfigured: boolean; llmAvailable: boolean; llmDailyLimit: number; }
interface Channel { id: string; name: string; kind: "email" | "discord"; owner_ref: number; group_id: string | null; enabled: boolean; revision: string; }
interface Rule { id: string; revision: string; definition: RuleDefinition; last_error: string | null; }
interface Activity { id: string; rule_name: string; subject_ref: number; summary: string; created_at: string; deliveries: Array<{ id: string; status: string; attempts: number }>; }
interface Access { permissions: Array<{ user_ref: number; can_edit: boolean; can_script: boolean; can_llm: boolean; group_ids: string[] }>; groups: Group[]; audit: Array<{ actor_ref: number; action: string; object_id: string; created_at: string }>; }
type Action = (method: string, path: string, body: unknown, done?: (result: Record<string, unknown>) => void) => Promise<void>;

const newRule = (userId: number): RuleDefinition => ({ name: "Low credits", audience: { type: "user", userId }, condition: { type: "compare", metric: "credits.available", operator: "<", value: 25 }, channelIds: [], subject: "Vox: {{rule}}", message: "Hello {{username}}, your balance is {{credits.available}} credits. {{result}}", intervalSeconds: 300, cooldownSeconds: 3600, enabled: false });
const ids = (text: string) => text.split(/[\s,]+/).filter(Boolean).map(Number);
const metricLabels: Record<string, string> = {
  "credits.available": "Available credits", "jobs.failed24h": "Failed personal jobs (24h)", "jobs.completed24h": "Completed personal jobs (24h)",
  "jobs.running": "Running personal jobs", "eval.responseLatencyMs": "Latest response latency (ms)", "eval.turnSuccessRate": "Latest turn success rate (0-1)",
};

export default function NotificationsPage() {
  const settings = useQuery<Settings>({ queryKey: [`${base}/settings`] });
  const channels = useQuery<Channel[]>({ queryKey: [`${base}/channels`] });
  const rules = useQuery<Rule[]>({ queryKey: [`${base}/rules`] });
  const activity = useQuery<Activity[]>({ queryKey: [`${base}/activity`], refetchInterval: 30_000 });
  const auth = useQuery<{ user: { id: number } }>({ queryKey: ["/api/auth/status"] });
  const [pending, setPending] = useState(false);
  const [error, setError] = useState("");
  const action: Action = async (method, path, body, done) => {
    setPending(true); setError("");
    try {
      const result = await (await apiRequest(method, `${base}${path}`, body)).json();
      done?.(result);
      for (const key of ["settings", "channels", "rules", "activity", "access"]) void queryClient.invalidateQueries({ queryKey: [`${base}/${key}`] });
    } catch (e) { setError((e as Error).message); }
    finally { setPending(false); }
  };
  if (settings.isLoading || auth.isLoading) return <p>Loading notification settings...</p>;
  if (settings.isError || !settings.data || !auth.data?.user) return <p role="alert">Could not load notification settings. Please reload.</p>;
  const config = settings.data;
  return <div className="mx-auto max-w-5xl space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-3 text-3xl font-semibold tracking-tight"><Bell className="h-7 w-7" /> Notifications</h1><p className="mt-2 text-muted-foreground">The right signal, delivered to the right person. Personal rules stay separate from organization billing.</p></div><Badge variant="outline">{config.permission.isAdmin ? "Admin" : config.permission.canEdit ? "Scout / Editor" : "Personal channels"}</Badge></div>
    {!config.encryptionConfigured && <p role="alert" className="rounded-lg border p-4 text-sm">Configure server encryption before adding channels or enabling rules.</p>}
    {error && <p role="alert" className="rounded-lg border border-destructive/30 p-4 text-sm text-destructive">{error}</p>}
    <Tabs defaultValue="channels"><TabsList className="mb-4 flex h-auto flex-wrap justify-start gap-1"><TabsTrigger value="channels"><Mail className="mr-2 h-4 w-4" />Channels</TabsTrigger><TabsTrigger value="rules"><Radio className="mr-2 h-4 w-4" />Rules &amp; Content</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger>{config.permission.isAdmin && <TabsTrigger value="access"><ShieldCheck className="mr-2 h-4 w-4" />Access &amp; Groups</TabsTrigger>}</TabsList>
      <TabsContent value="channels"><Channels config={config} channels={channels.data ?? []} action={action} pending={pending} />{channels.isError && <p role="alert">Could not load channels.</p>}</TabsContent>
      <TabsContent value="rules"><Rules config={config} channels={channels.data ?? []} rules={rules.data ?? []} userId={auth.data.user.id} action={action} pending={pending} />{rules.isError && <p role="alert">Could not load rules.</p>}</TabsContent>
      <TabsContent value="activity"><Card><CardHeader><CardTitle>Delivery activity</CardTitle><CardDescription>Recent triggers and delivery attempts. Bodies and webhook credentials are never shown here.</CardDescription></CardHeader><CardContent className="space-y-4">{activity.isError ? <p role="alert">Could not load activity.</p> : !activity.data?.length ? <p className="text-sm text-muted-foreground">No notifications have fired yet.</p> : activity.data.map((item) => <div key={item.id} className="space-y-2 border-b pb-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{item.rule_name || "Notification"} <span className="text-sm text-muted-foreground">&middot; User #{item.subject_ref}</span></p><time className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</time></div><p className="break-words text-sm">{item.summary}</p><div className="flex flex-wrap gap-2">{item.deliveries.map((delivery) => <Badge key={delivery.id} variant="outline">{delivery.status} &middot; {delivery.attempts} attempts</Badge>)}{!item.deliveries.length && <Badge variant="outline">No enabled / verified destination</Badge>}</div></div>)}</CardContent></Card></TabsContent>
      {config.permission.isAdmin && <TabsContent value="access"><AccessPanel action={action} pending={pending} /></TabsContent>}
    </Tabs>
  </div>;
}

function Channels({ config, channels, action, pending }: { config: Settings; channels: Channel[]; action: Action; pending: boolean }) {
  const [name, setName] = useState("");
  const [kind, setKind] = useState<"email" | "discord">("email");
  const [groupId, setGroupId] = useState("");
  const [webhook, setWebhook] = useState("");
  const [editing, setEditing] = useState<Channel | null>(null);
  const allowedGroups = config.permission.isAdmin ? config.groups : config.groups.filter((group) => config.permission.canEdit && config.permission.groupIds.includes(group.id));
  return <div className="space-y-5"><Card><CardHeader><CardTitle>Your channels</CardTitle><CardDescription>Email uses the recipient's verified account address. Discord uses an encrypted webhook; mentions are disabled.</CardDescription></CardHeader><CardContent className="space-y-3">{!channels.length && <p className="text-sm text-muted-foreground">Add a channel to receive alerts.</p>}{channels.map((channel) => <div key={channel.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{channel.name}</p><p className="text-xs text-muted-foreground">{channel.kind} &middot; {channel.group_id ? config.groups.find((group) => group.id === channel.group_id)?.name ?? "Group" : `User #${channel.owner_ref}`}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{channel.enabled ? "Enabled" : "Paused"}</Badge><Button size="sm" variant="outline" disabled={pending} onClick={() => { setEditing(channel); setName(channel.name); setKind(channel.kind); setGroupId(channel.group_id ?? ""); setWebhook(""); }}>Edit</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => action("PATCH", `/channels/${channel.id}`, { revision: channel.revision, name: channel.name, enabled: !channel.enabled })}>{channel.enabled ? "Pause" : "Enable"}</Button></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>{editing ? "Edit channel" : "Add channel"}</CardTitle><CardDescription>{config.emailAvailable ? "Email delivery is configured." : "SMTP is not configured. Discord can work independently."} WhatsApp and SMS are reserved for future adapters.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const body = editing ? { revision: editing.revision, name, enabled: editing.enabled, ...(webhook ? { webhookUrl: webhook } : {}) } : { name, kind, groupId: groupId || null, ...(kind === "discord" ? { webhookUrl: webhook } : {}) }; void action(editing ? "PATCH" : "POST", editing ? `/channels/${editing.id}` : "/channels", body, () => { setEditing(null); setName(""); setWebhook(""); }); }}>
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="channel-name">Name</Label><Input id="channel-name" value={name} maxLength={80} required onChange={(e) => setName(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="channel-kind">Channel</Label><select id="channel-kind" className={selectStyle} disabled={!!editing} value={kind} onChange={(e) => setKind(e.target.value as "email" | "discord")}><option value="email">Email</option><option value="discord">Discord</option></select></div></div>
      <div className="space-y-2"><Label htmlFor="channel-audience">Audience</Label><select id="channel-audience" className={selectStyle} disabled={!!editing} value={groupId} onChange={(e) => setGroupId(e.target.value)}><option value="">My account</option>{allowedGroups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div>
      {kind === "discord" && <div className="space-y-2"><Label htmlFor="channel-webhook">Discord webhook URL {editing && "(leave blank to keep it)"}</Label><Input id="channel-webhook" type="password" autoComplete="off" value={webhook} maxLength={300} required={!editing} onChange={(e) => setWebhook(e.target.value)} /><p className="text-xs text-muted-foreground">Only official discord.com / discordapp.com HTTPS webhooks are accepted. Saved URLs are never returned.</p></div>}
      <div className="flex gap-2"><Button disabled={pending || !config.encryptionConfigured} type="submit">{editing ? "Save channel" : "Add channel"}</Button>{editing && <Button type="button" variant="outline" onClick={() => { setEditing(null); setName(""); setWebhook(""); }}>Cancel edit</Button>}</div>
    </form></CardContent></Card></div>;
}

function Rules({ config, channels, rules, userId, action, pending }: { config: Settings; channels: Channel[]; rules: Rule[]; userId: number; action: Action; pending: boolean }) {
  const [definition, setDefinition] = useState<RuleDefinition>(() => newRule(userId));
  const [editing, setEditing] = useState<Rule | null>(null);
  const [preview, setPreview] = useState<{ matched: boolean; summary: string; subjectId: number } | null>(null);
  const set = (patch: Partial<RuleDefinition>) => { setDefinition((current) => ({ ...current, ...patch })); setPreview(null); };
  const groups = config.permission.isAdmin ? config.groups : config.groups.filter((group) => config.permission.groupIds.includes(group.id));
  const eligible = channels.filter((channel) => definition.audience.type === "group" ? channel.group_id === definition.audience.groupId : channel.group_id === null && channel.owner_ref === definition.audience.userId);
  return <div className="space-y-5"><Card><CardHeader><CardTitle>Trigger rules</CardTitle><CardDescription>Compare the latest values, calculate with JavaScript, or ask a configured LLM to analyze the numeric data.</CardDescription></CardHeader><CardContent className="space-y-3">{!config.permission.canEdit && <p className="text-sm text-muted-foreground">An admin can assign Scout / Editor access for your account or selected groups. Paid plans do not grant editing permission.</p>}{!rules.length && <p className="text-sm text-muted-foreground">No rules configured for this audience yet.</p>}{rules.map((rule) => <div key={rule.id} className="flex flex-wrap items-start justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{rule.definition.name}</p><p className="text-xs text-muted-foreground">{rule.definition.condition.type} &middot; every {rule.definition.intervalSeconds / 60} min &middot; {rule.definition.enabled ? "Enabled" : "Paused"}</p>{rule.last_error && <p role="alert" className="mt-2 text-xs text-destructive">{rule.last_error}</p>}</div>{config.permission.canEdit && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => { setEditing(rule); setDefinition(rule.definition); setPreview(null); }}>Edit</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => action("PATCH", `/rules/${rule.id}`, { revision: rule.revision, definition: { ...rule.definition, enabled: !rule.definition.enabled } })}>{rule.definition.enabled ? "Pause" : "Enable"}</Button></div>}</div>)}</CardContent></Card>
    {config.permission.canEdit && <Card><CardHeader><CardTitle>{editing ? "Edit rule & content" : "Create rule & content"}</CardTitle><CardDescription>Preview does not send a message. New rules start paused; enable when ready.</CardDescription></CardHeader><CardContent><form className="space-y-5" onSubmit={(event) => { event.preventDefault(); void action(editing ? "PATCH" : "POST", editing ? `/rules/${editing.id}` : "/rules", editing ? { revision: editing.revision, definition } : definition, () => { setEditing(null); setDefinition(newRule(userId)); setPreview(null); }); }}>
      <div className="space-y-2"><Label htmlFor="rule-name">Rule name</Label><Input id="rule-name" required value={definition.name} maxLength={100} onChange={(e) => set({ name: e.target.value })} /></div>
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="rule-audience">Audience</Label><select id="rule-audience" className={selectStyle} value={definition.audience.type === "group" ? definition.audience.groupId : "user"} onChange={(e) => set({ audience: e.target.value === "user" ? { type: "user", userId } : { type: "group", groupId: e.target.value }, channelIds: [] })}><option value="user">Personal account</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div>{definition.audience.type === "user" && config.permission.isAdmin && <div className="space-y-2"><Label htmlFor="rule-user">Recipient user ID</Label><Input id="rule-user" type="number" min={1} value={definition.audience.userId} onChange={(e) => set({ audience: { type: "user", userId: Number(e.target.value) }, channelIds: [] })} /></div>}</div>
      <fieldset className="space-y-2"><legend className="text-sm font-medium">Channels</legend>{!eligible.length && <p className="text-xs text-muted-foreground">Add a channel for this audience first. Individual recipients manage their own destinations.</p>}{eligible.map((channel) => <label key={channel.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={definition.channelIds.includes(channel.id)} onChange={(e) => set({ channelIds: e.target.checked ? [...definition.channelIds, channel.id] : definition.channelIds.filter((id) => id !== channel.id) })} />{channel.name} ({channel.kind}{!channel.enabled && ", paused"})</label>)}</fieldset>
      <div className="space-y-2"><Label htmlFor="rule-mode">Trigger mode</Label><select id="rule-mode" className={selectStyle} value={definition.condition.type} onChange={(e) => set({ condition: e.target.value === "javascript" ? { type: "javascript", code: 'return { matched: data.metrics["credits.available"] < 25, summary: "Low credits" };' } : e.target.value === "llm" ? { type: "llm", prompt: "Trigger when recent personal evaluations show a meaningful increase in response latency. Explain briefly." } : { type: "compare", metric: "credits.available", operator: "<", value: 25 }, intervalSeconds: e.target.value === "llm" ? Math.max(900, definition.intervalSeconds) : definition.intervalSeconds })}><option value="compare">Compare latest value</option><option value="javascript" disabled={!config.permission.canScript}>JavaScript calculation</option><option value="llm" disabled={!config.permission.canLlm || !config.llmAvailable}>LLM analysis {!config.llmAvailable && "(not configured)"}</option></select></div>
      {definition.condition.type === "compare" && <div className="grid gap-3 sm:grid-cols-3"><div className="space-y-2"><Label htmlFor="rule-metric">Metric</Label><select id="rule-metric" className={selectStyle} value={definition.condition.metric} onChange={(e) => { if (definition.condition.type === "compare") set({ condition: { ...definition.condition, metric: e.target.value as typeof definition.condition.metric } }); }}>{config.metrics.map((metric) => <option value={metric} key={metric}>{metricLabels[metric] ?? metric}</option>)}</select></div><div className="space-y-2"><Label htmlFor="rule-operator">Operator</Label><select id="rule-operator" className={selectStyle} value={definition.condition.operator} onChange={(e) => { if (definition.condition.type === "compare") set({ condition: { ...definition.condition, operator: e.target.value as typeof definition.condition.operator } }); }}>{["<", "<=", "=", "!=", ">=", ">"].map((operator) => <option key={operator}>{operator}</option>)}</select></div><div className="space-y-2"><Label htmlFor="rule-threshold">Threshold</Label><Input id="rule-threshold" type="number" step="any" required value={definition.condition.value} onChange={(e) => { if (definition.condition.type === "compare") set({ condition: { ...definition.condition, value: Number(e.target.value) } }); }} /></div></div>}
      {definition.condition.type === "javascript" && <div className="space-y-2"><Label htmlFor="rule-script">JavaScript</Label><textarea id="rule-script" className={`${textareaStyle} font-mono`} rows={6} maxLength={8192} value={definition.condition.code} onChange={(e) => set({ condition: { type: "javascript", code: e.target.value } })} /><p className="text-xs text-muted-foreground">Use data.metrics, latest, or loadData().samples (up to 50 recent personal results). Return a boolean or &#123; matched, summary &#125;. No network, files, secrets or Node APIs; 50 ms / 8 MB limits.</p></div>}
      {definition.condition.type === "llm" && <div className="space-y-2"><Label htmlFor="rule-prompt">Analysis instructions</Label><textarea id="rule-prompt" className={textareaStyle} rows={4} minLength={10} maxLength={2000} value={definition.condition.prompt} onChange={(e) => set({ condition: { type: "llm", prompt: e.target.value } })} /><p className="text-xs text-muted-foreground">Numeric monitoring data goes to the configured external provider. Preview uses the shared daily budget ({config.llmDailyLimit} requests). Identity fields and transcripts are not added to the data. Do not put secrets or personal data in instructions.</p></div>}
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="rule-interval">Check interval (seconds)</Label><Input id="rule-interval" type="number" required min={definition.condition.type === "llm" ? 900 : 60} max={86400} value={definition.intervalSeconds} onChange={(e) => set({ intervalSeconds: Number(e.target.value) })} /></div><div className="space-y-2"><Label htmlFor="rule-cooldown">Minimum time between alerts (seconds)</Label><Input id="rule-cooldown" type="number" required min={300} max={604800} value={definition.cooldownSeconds} onChange={(e) => set({ cooldownSeconds: Number(e.target.value) })} /></div></div>
      <div className="space-y-2"><Label htmlFor="rule-subject">Subject</Label><Input id="rule-subject" maxLength={160} required value={definition.subject} onChange={(e) => set({ subject: e.target.value })} /></div><div className="space-y-2"><Label htmlFor="rule-message">Message template</Label><textarea id="rule-message" className={textareaStyle} maxLength={1500} required value={definition.message} onChange={(e) => set({ message: e.target.value })} /><p className="text-xs text-muted-foreground">Placeholders: &#123;&#123;username&#125;&#125;, &#123;&#123;rule&#125;&#125;, &#123;&#123;result&#125;&#125;, or a metric key such as &#123;&#123;credits.available&#125;&#125;.</p></div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={definition.enabled} onChange={(e) => set({ enabled: e.target.checked })} />Enable this rule</label>
      {preview && <p role="status" className="rounded-lg border p-3 text-sm">Preview for user #{preview.subjectId}: {preview.matched ? "Would trigger" : "Would not trigger"}. {preview.summary}</p>}
      <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={pending || !definition.channelIds.length} onClick={() => action("POST", "/preview", definition, (result) => setPreview(result as unknown as typeof preview))}>Preview rule</Button><Button type="submit" disabled={pending || !config.encryptionConfigured || !definition.channelIds.length}>{editing ? "Save rule" : "Create rule"}</Button>{editing && <Button type="button" variant="outline" onClick={() => { setEditing(null); setDefinition(newRule(userId)); setPreview(null); }}>Cancel edit</Button>}</div>
    </form></CardContent></Card>}
  </div>;
}

function AccessPanel({ action, pending }: { action: Action; pending: boolean }) {
  const access = useQuery<Access>({ queryKey: [`${base}/access`] });
  const [userId, setUserId] = useState("");
  const [canEdit, setCanEdit] = useState(false);
  const [canScript, setCanScript] = useState(false);
  const [canLlm, setCanLlm] = useState(false);
  const [groupIds, setGroupIds] = useState<string[]>([]);
  const [groupName, setGroupName] = useState("");
  const [members, setMembers] = useState("");
  const [editingGroup, setEditingGroup] = useState("");
  return <div className="space-y-5"><Card><CardHeader><CardTitle>Scout / Editor permissions</CardTitle><CardDescription>Explicitly assign access. This does not change account plans, admin rights, or organization membership.</CardDescription></CardHeader><CardContent className="space-y-4">{access.isError && <p role="alert">Could not load access settings.</p>}{access.data?.permissions.map((permission) => <div key={permission.user_ref} className="flex flex-wrap items-center justify-between gap-3 border-b pb-3"><p className="text-sm">User #{permission.user_ref} &middot; {permission.can_edit ? "Editor" : "No editing"}{permission.can_script && " / JavaScript"}{permission.can_llm && " / LLM"}</p><Button size="sm" variant="outline" onClick={() => { setUserId(String(permission.user_ref)); setCanEdit(permission.can_edit); setCanScript(permission.can_script); setCanLlm(permission.can_llm); setGroupIds(permission.group_ids); }}>Edit access</Button></div>)}<form className="space-y-4" onSubmit={(e) => { e.preventDefault(); void action("POST", "/access", { userId: Number(userId), canEdit, canScript: canEdit && canScript, canLlm: canEdit && canLlm, groupIds }); }}><div className="space-y-2"><Label htmlFor="editor-user">User ID</Label><Input id="editor-user" type="number" min={1} required value={userId} onChange={(e) => setUserId(e.target.value)} /></div><div className="flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={canEdit} onChange={(e) => setCanEdit(e.target.checked)} />Edit rules &amp; content</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={!canEdit} checked={canScript} onChange={(e) => setCanScript(e.target.checked)} />JavaScript</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={!canEdit} checked={canLlm} onChange={(e) => setCanLlm(e.target.checked)} />LLM</label></div><fieldset className="space-y-2"><legend className="text-sm font-medium">Assigned groups</legend>{access.data?.groups.map((group) => <label key={group.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={groupIds.includes(group.id)} onChange={(e) => setGroupIds(e.target.checked ? [...groupIds, group.id] : groupIds.filter((id) => id !== group.id))} />{group.name}</label>)}</fieldset><Button disabled={pending}>Save access</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Notification audiences</CardTitle><CardDescription>Groups select recipients for per-user evaluation. They are plugin-owned audiences, not organizations.</CardDescription></CardHeader><CardContent className="space-y-4">{access.data?.groups.map((group) => <div key={group.id} className="flex flex-wrap items-center justify-between gap-3 border-b pb-3"><p className="text-sm">{group.name} &middot; {group.user_refs?.length ?? 0} members</p><Button size="sm" variant="outline" onClick={() => { setEditingGroup(group.id); setGroupName(group.name); setMembers(group.user_refs?.join(", ") ?? ""); }}>Edit audience</Button></div>)}<form className="space-y-4" onSubmit={(e) => { e.preventDefault(); void action(editingGroup ? "PATCH" : "POST", editingGroup ? `/groups/${editingGroup}` : "/groups", { name: groupName, userIds: ids(members) }, () => { setGroupName(""); setMembers(""); setEditingGroup(""); }); }}><div className="space-y-2"><Label htmlFor="group-name">Group name</Label><Input id="group-name" required maxLength={80} value={groupName} onChange={(e) => setGroupName(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="group-members">Recipient user IDs (comma separated)</Label><Input id="group-members" required value={members} onChange={(e) => setMembers(e.target.value)} /><p className="text-xs text-muted-foreground">Maximum 100 members. Removing a member also cancels their queued alerts.</p></div><div className="flex gap-2"><Button disabled={pending}>{editingGroup ? "Save audience" : "Create audience"}</Button>{editingGroup && <Button type="button" variant="outline" onClick={() => { setEditingGroup(""); setGroupName(""); setMembers(""); }}>Cancel edit</Button>}</div></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Configuration audit</CardTitle></CardHeader><CardContent className="space-y-2">{access.data?.audit.slice(0, 15).map((entry, index) => <p key={index} className="break-all text-xs text-muted-foreground">{new Date(entry.created_at).toLocaleString()} &middot; User #{entry.actor_ref} &middot; {entry.action} &middot; {entry.object_id}</p>)}</CardContent></Card>
  </div>;
}
